### ISSUE TITLE
发送动图出错

### ISSUE THREAD

**Issue by decatri** [anlen123/nonebot_plugin_pixiv#26]
12-16 20:20:52 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_pixiv, lineno=103) failed.
Traceback (most recent call last):
  File "F:\nb2-fast-deploy-main\nb2-fast-deploy-main\bot.py", line 67, in <module>
    nonebot.run()
  File "F:\nb2-fast-deploy-main\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "F:\nb2-fast-deploy-main\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 201, in run
    uvicorn.run(
  File "F:\nb2-fast-deploy-main\nb2-fast-deploy-main\.venv\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "F:\nb2-fast-deploy-main\nb2-fast-deploy-main\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\atri\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\atri\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\atri\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\atri\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\atri\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\atri\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "F:\nb2-fast-deploy-main\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "F:\nb2-fast-deploy-main\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "F:\nb2-fast-deploy-main\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 846, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "F:\nb2-fast-deploy-main\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 821, in simple_run
    await handler(
  File "F:\nb2-fast-deploy-main\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "F:\nb2-fast-deploy-main\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot_plugin_pixiv\__init__.py", line 114, in pixiv_rev
    await GIF_send(xx, PID, event, bot)
  File "F:\nb2-fast-deploy-main\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot_plugin_pixiv\__init__.py", line 327, in GIF_send
    size = os.path.getsize(f"{path_pre}/{PID}.gif")
  File "C:\Users\atri\AppData\Local\Programs\Python\Python310\lib\genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'F:\\nb2-fast-deploy-main\\nb2-fast-deploy-main\\data\\rootQQbotFiles/pixivZip/114275911/114275911.gif'

**Comment by YipSzeho** [comment]
同样遇到这个问题，Ubuntu22.04.3
